  CREATE USER TEST
  IDENTIFIED BY TEST
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;

  GRANT CONNECT TO TEST WITH ADMIN OPTION;
  GRANT DBA TO TEST WITH ADMIN OPTION;
  ALTER USER TEST DEFAULT ROLE ALL;
  GRANT ALTER USER TO TEST;
  GRANT CREATE ANY INDEX TO TEST;
  GRANT CREATE ANY SYNONYM TO TEST;
  GRANT CREATE ANY TABLE TO TEST;
  GRANT CREATE ANY TRIGGER TO TEST;
  GRANT CREATE ANY VIEW TO TEST;
  GRANT CREATE SYNONYM TO TEST;
  GRANT CREATE TABLE TO TEST;
  GRANT CREATE TRIGGER TO TEST;
  GRANT CREATE USER TO TEST;
  GRANT DELETE ANY TABLE TO TEST;
  GRANT DROP ANY INDEX TO TEST;
  GRANT DROP ANY SYNONYM TO TEST;
  GRANT DROP ANY TABLE TO TEST;
  GRANT DROP ANY TRIGGER TO TEST;
  GRANT DROP ANY VIEW TO TEST;
  GRANT EXECUTE ANY PROCEDURE TO TEST WITH ADMIN OPTION;
  GRANT GRANT ANY PRIVILEGE TO TEST WITH ADMIN OPTION;
  GRANT INSERT ANY TABLE TO TEST;
  GRANT SELECT ANY TABLE TO TEST WITH ADMIN OPTION;
  GRANT UNLIMITED TABLESPACE TO TEST WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO TEST;
  
  ALTER USER TEST QUOTA UNLIMITED ON USERS;
  
  GRANT EXECUTE ON SYS.DBMS_NETWORK_ACL_ADMIN TO TEST;
    GRANT EXECUTE ON SYS.SYS_PLSQL_4D9DBC49_9_1 TO TEST WITH GRANT      OPTION;
    GRANT EXECUTE ON SYS.UTL_HTTP TO TEST;
    GRANT EXECUTE ON SYS.UTL_INADDR TO TEST;
    GRANT EXECUTE ON SYS.UTL_SMTP TO TEST;
    GRANT EXECUTE ON SYS.UTL_TCP TO TEST;
    GRANT SELECT ON SYS.V_$SESSION TO TEST;
    
    
    BEGIN
    DBMS_EPG.create_dad (
    dad_name => 'xml_demo',
    path     => '/xml_demo/*');
    END;
    /

    BEGIN
    DBMS_EPG.authorize_dad (
    dad_name => 'xml_demo',
    user     => 'TEST');
    END;
    /

    BEGIN
      dbms_network_acl_admin.create_acl('localhost1.xml', 'ACL for localhost', 'TEST', TRUE, 'connect');
      dbms_network_acl_admin.assign_acl('localhost1.xml', 'localhost');
    END;
    /
    COMMIT
    /
    
    CREATE TABLE test.emp AS SELECT * FROM scott.emp;
    CREATE TABLE test.dept AS SELECT * FROM scott.dept;

    ALTER USER SCOTT IDENTIFIED BY SCOTT ACCOUNT UNLOCK;
    
    SELECT DBMS_XDB.gethttpport FROM dual;
    
    EXEC DBMS_XDB.sethttpport(8080);